Atelier_Project/urls.py
from django.contrib import admin  # Importo admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Atelier_Shop import views
from Product import views as P_views

urlpatterns = [
    path('admin/', admin.site.urls),  # Shto admin panelin
    path('', views.index, name='index'),
    path('new_arrivals/', P_views.new_arrivals, name='new_arrivals'),
    path('category_page/<int:category_id>/', P_views.category_page, name='category_page'),
    path('shop/', P_views.shop, name='shop'),
    path('collection/', P_views.collection, name='collection'),
    path('collection_page/<slug:collection_slug>/', P_views.collection_page, name='collection_page'),
    path('product/<int:product_id>/', P_views.product, name='product'),
    path('addToCart/', P_views.addToCart, name='addToCart'),
    path('cart_modal/', P_views.cart_modal, name='cart_modal'),
    path('gifts-under-100/', P_views.gifts_under_100, name='gifts_under_100'),
    path('gifts-100-150/', P_views.gifts_100_150, name='gifts_100_150'),
    path('gifts-over-150/', P_views.gifts_over_150, name='gifts_over_150'),
    path('update_item/', P_views.update_item, name='update_item'),
    path('checkout/', P_views.checkout, name='checkout'),
    path('message/', views.message, name='message'),
    path('success/', views.message, name='success'),

    path('initiate_payment/<str:order_id>/', P_views.initiate_payment, name='initiate_payment'),
    path('payment_gateway/<str:order_id>/<str:mac>/<str:customer_email>/<str:amount_in_cents>', P_views.payment_gateway, name='payment_gateway'),
    path('payment_success/', P_views.payment_success, name='payment_success'),
    path('payment_canceled/', P_views.payment_canceled, name='payment_canceled'),
    path('notifications/', P_views.notifications, name='notifications'),
    path('elements/', P_views.elements, name='elements'),
    path('process_order_online/', P_views.process_order_online, name='process_order_online'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    # path('paypal/<int:order_id>/<int:amount_in_cents>/', P_views.paypal, name='paypal')
    path('paypal/<str:order_id>/', P_views.paypal, name='paypal'),
    path('payment-success/', P_views.payment_success, name='payment_success'),
    path('payment-cancelled/', P_views.payment_canceled, name='payment_canceled'),
    path('paypal-ipn/', P_views.paypal_ipn, name='paypal_ipn'),  # për IPN
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Atelier_Shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Product/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils.text import slugify  # Importo slugify
import uuid

class A_Category(models.Model):
    category = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.category

class B_Subcategory(models.Model):
    category = models.ForeignKey(A_Category, on_delete=models.CASCADE, null=True, blank=True)
    subcategory = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.category.category + ': ' + self.subcategory

class C_Collection(models.Model):
    collection = models.CharField(max_length=100, default='')
    slug = models.SlugField(unique=True, blank=True)
    main_image = models.ImageField(null=True, blank=True)
    info = models.CharField(max_length=200, default='')
    description = RichTextField(blank=True, null=True)
    cover_image = models.ImageField(null=True, blank=True)
    footer_description = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:  # Krijo slug automatikisht nëse nuk është dhënë
            self.slug = slugify(self.collection)
        # Sigurohuni që slug është unik
        while C_Collection.objects.filter(slug=self.slug).exists():
            self.slug = f"{self.slug}-{self.id}"  # Shtoni një identifikues unik
        super(C_Collection, self).save(*args, **kwargs)

    def __str__(self):
        return self.collection

class C_Gift(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)
    price_category = models.CharField(
        max_length=20, choices=[
            ('under_100', 'Under 100$'),
            ('between_100_150', 'Between 100$ and 150$'),
            ('over_150', 'Over 150$'),
        ], default='under_100'
    )

    def __str__(self):
        return self.name

class D_Product(models.Model):
    name = models.CharField(max_length=100, default='')
    subcategory = models.ForeignKey(B_Subcategory, on_delete=models.CASCADE, null=True, blank=True)
    collection = models.ForeignKey(C_Collection, on_delete=models.CASCADE, related_name='products', null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    main_image = models.ImageField(null=True, blank=True)
    description = RichTextField(blank=True, null=True)
    details = RichTextField(blank=True, null=True)
    is_new = models.BooleanField(default=False)

    @property
    def imageURL(self):
        try:
            url = self.main_image.url
        except:
            url = ''
        return url

    def __str__(self):
        # Sigurohuni që subcategory dhe category janë të disponueshme
        category_name = self.subcategory.category.category if self.subcategory and self.subcategory.category else 'No Category'
        return f'{category_name}: {self.subcategory.subcategory}: {self.name}'

    # def __str__(self):
    #     return self.subcategory.category.category + ': ' + self.subcategory.subcategory + ': ' + self.name

class D_Colors_List(models.Model):
    color = models.CharField(max_length=100, default='')
    code = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.color

class E_Product_Gallery(models.Model):
    product = models.ForeignKey(D_Product, on_delete=models.CASCADE, null=True, blank=True, related_name='images')
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.product.name

class E_Product_Color(models.Model):
    product = models.ForeignKey(D_Product, on_delete=models.CASCADE, null=True, blank=True)
    color = models.ForeignKey(D_Colors_List, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.product.name + ', ' + self.color.color

class E_Product_Size(models.Model):
    product = models.ForeignKey(D_Product, on_delete=models.CASCADE, null=True, blank=True)
    size = models.CharField(max_length=10, default='')

    def __str__(self):
        return self.product.name + ', ' + self.size

class G_Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='g_customer')  # Changed related_name
    name = models.CharField(max_length=50, default='', blank=True)
    surname = models.CharField(max_length=50, default='', blank=True)
    email = models.EmailField(max_length=100, null=True)
    session_id = models.CharField(max_length=100, null=True, blank=True)

    # def __str__(self):
    #     return self.name + ' ' + self.surname
    def __str__(self):
        return self.user.username if self.user else f"Guest {self.session_id}"
#
# class H_Order(models.Model):
#     customer = models.ForeignKey(G_Customer, on_delete=models.SET_NULL, null=True, blank=True)
#     date_ordered = models.DateTimeField(auto_now_add=True)
#     complete = models.BooleanField(default=False, null=True, blank=False)
#     transaction_id = models.CharField(max_length=100, null=True)
#     session_key = models.CharField(max_length=40, null=True, blank=True)
#     order_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
#
#     @property
#     def get_cart_total(self):
#         orderitems = self.i_orderitem_set.all()
#         total = sum([item.get_total for item in orderitems])
#         return total
#
#     @property
#     def get_cart_items(self):
#         orderitems = self.i_orderitem_set.all()
#         total = sum([item.quantity for item in orderitems])
#         return total
#
#     @property
#     def get_order_id(self):
#         order_id = self.id
#         return order_id
#
#     def __str__(self):
#         return 'Order ID: ' + str(self.id) + ', Customer: ' + self.customer.name + ' ' + self.customer.surname

class H_Order(models.Model):
    customer = models.ForeignKey(G_Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=100, null=True)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    order_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    @property
    def get_cart_total(self):
        orderitems = self.i_orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.i_orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def get_order_id(self):
        order_id = self.id
        return order_id

    def __str__(self):
        if self.customer:
            return f'Order ID: {self.id}, Customer: {self.customer.name} {self.customer.surname}'
        else:
            return f'Order ID: {self.id}, Customer: Unknown'

class I_OrderItem(models.Model):
    product = models.ForeignKey(D_Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(H_Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    size = models.CharField(max_length=30, null=True)
    color = models.CharField(max_length=50, null=True)

    # @property
    # def get_total(self):
    #     total = self.product.price * self.quantity
    #     return total
    @property
    def get_total(self):
        if self.product and self.quantity:
            return self.product.price * self.quantity
        return 0

    # def __str__(self):
    #     return 'Order ID: ' + str(self.order.id) + ', ' + 'Product: ' + self.product.name + ', Quantity: ' + str(self.quantity)
    def __str__(self):
        order_id = self.order.id if self.order else 'N/A'
        product_name = self.product.name if self.product else 'Product deleted'
        quantity = self.quantity if self.quantity else 0
        return f'Order ID: {order_id}, Product: {product_name}, Quantity: {quantity}'

class J_ShippingAddres(models.Model):
    customer = models.ForeignKey(G_Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(H_Order, on_delete=models.SET_NULL, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    zipcode = models.CharField(max_length=100, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=100, null=True, default='')
    coupon = models.CharField(max_length=100, null=True, default='', blank=True)

    # def __str__(self):
    #     return 'Order: ' + str(self.order.) + ', ' + self.email

class K_Cupon(models.Model):
    code = models.CharField(max_length=100, null=True)
    discount = models.IntegerField(default=0)

    def __str__(self):
        return 'Code: ' + self.code + ', Discount: ' + str(self.discount) + '%'

class K_Cupon_Order(models.Model):
    order = models.ForeignKey(H_Order, on_delete=models.SET_NULL, null=True, blank=True)
    discount = models.DecimalField(max_digits=7, decimal_places=2, default=0)

templates/cart_modal.html
{% load static %}
<div class="modal-header">
  <h2 class="text-sm">Shopping cart <span class="cart-count">{{ cartItems }}</span></h2>
  <button class="close-modal text-sm">&times;</button>
</div>

<div class="cart-body">
  <div class="cart-items">
    {% for item in items %}
    <div class="cart-item">
      <div class="img-box">
        <img src="{{ item.product.imageURL }}" class="img-fluid">
      </div>
      <div class="item-info">
        <div class="item-actions">
          <h3 class="text-small">{{ item.product.name }}</h3>
          <p class="variant text-small">Size: {{ item.size }}</p>
        </div>
<div class="quantity-selector">
  <button
    class="decrement text-small update-cart"
    data-action="remove"
    data-product="{{ item.product.id }}"
    data-size="{{ item.size }}">
    -
  </button>

  <span class="quantity text-small">{{ item.quantity }}</span>

  <button
    class="increment text-small update-cart"
    data-action="add"
    data-product="{{ item.product.id }}"
    data-size="{{ item.size }}">
    +
  </button>
</div>
      </div>
      <div class="item-p">
        <div class="item-price text-small">{{ item.get_total|floatformat:0 }} EUR</div>
        <div class="action-buttons">
          <button class="favorite text-small-h">Add to Favorites</button>
          <button class="remove-item update-cart text-small-h" data-product="{{ item.product.id }}" data-action="remove">Remove</button>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="cart-summary">
    <div class="total">
      <span class="text-small">TOTAL</span>
      <span class="amount text-small">{{ order.get_cart_total|floatformat:2 }} EUR</span>
    </div>
    <p class="vat-notice text-sm">VAT Included</p>
  </div>

  <div class="checkout-actions">
    <a href="/checkout/" class="checkout-btn btn-thm">PROCEED TO CHECKOUT</a>
    <button class="paypal-btn">PayPal</button>
  </div>

  <div class="legal-notice">
    <p class="text-sm">By making this payment, you accept the General Conditions of Sale and confirm that you have read and understand the Privacy Policy.</p>
  </div>

  <div class="footer-links-cart">
    <a href="/addToCart/" class="view-cart btn-thm">VIEW MY SHOPPING CART</a>
    <div class="help-section">
      <p>Need help? Contact us</p>
      <div class="help">
      <p>Monday to Friday from 09:00AM to 8 PM ET.</p>
      <div class="contact-methods">
        <a href="#" class="call text-small">Call</a>
        <a href="#" class="email text-small">Email</a>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="secure-pay">
    <h4 class="text-small">Secure payment</h4>
    <div class="secure">
    <div class="img-secure">
      <img src="/static/images/visa.png" alt="visa-logo">
    </div>
    <div class="img-secure">
      <img src="/static/images/mastercard.png" alt="mastercard-logo">
    </div>
    <div class="img-secure">
      <img src="/static/images/paypal.jpeg" alt="paypal-logo">
    </div>
  </div>
  </div>
</div>

templates/footer.html
{% load static %}
<footer class="site-footer">
  <div class="newsletter-section">
    <div class="newsletter-flex">
    <div class="newsletter-text">
      <h3 class="text-medium">Subscribe to the newsletter</h3>
      <p class="text-sm">Subscribe to receive all the information by email on our latest collections, our products, our fashion shows and our projects.</p>
    </div>
    <form class="newsletter-form">
      <input type="email" placeholder="Email" required>
      <button type="submit">...</button>
      <p class="newsletter-note">
        I agree to receive the JACQUEMUS newsletter to be the first to know about new collections, exclusive product launches, events and services available. By subscribing, I agree to the JACQUEMUS Privacy Policy.
      </p>
    </form>
    </div>
      <div class="footer-column-flex">
      <ul>
        <h4 class="text-sm"><a href="#">Customer Care</a></h4>
        <li class="text-sm"><a href="#">Contact form</a></li>
        <li class="text-sm"><a href="#">Register a return</a></li>
      </ul>
    </div>
    <div class="country-region">
      <h4 class="text-sm">Country/Region</h4>
      <p class="text-sm">🇦🇱 Albania (EUR) | English ▼</p>
    </div>
  </div>

  <hr class="footer-divider" />

  <div class="footer-links">
    <div class="footer-column">
      <h4 class="text-sm">Legal</h4>
      <ul>
        <li class="text-sm"><a href="#">Legal notice</a></li>
        <li class="text-sm"><a href="#">Terms of sale</a></li>
        <li class="text-sm"><a href="#">Privacy policy</a></li>
        <li class="text-sm"><a href="#">Terms of Use</a></li>
        <li class="text-sm"><a href="#">Accessibility</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4 class="text-sm">FAQ</h4>
      <ul>
        <li class="text-sm"><a href="#">Account</a></li>
        <li class="text-sm"><a href="#">Shipping informations</a></li>
        <li class="text-sm"><a href="#">Orders</a></li>
        <li class="text-sm"><a href="#">Payments</a></li>
        <li class="text-sm"><a href="#">Returns & exchanges</a></li>
        <li class="text-sm"><a href="#">Size guide</a></li>
        <li class="text-sm"><a href="#">Gift Card</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4 class="text-sm">Company</h4>
      <ul>
        <li class="text-sm"><a href="#">Contact us</a></li>
        <li class="text-sm"><a href="#">Stores</a></li>
        <li class="text-sm"><a href="#">Book an appointment in store</a></li>
        <li class="text-sm"><a href="#">Career</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4 class="text-sm">Follow</h4>
      <ul>
        <li class="text-sm"><a href="#">Instagram</a></li>
        <li class="text-sm"><a href="#">Facebook</a></li>
        <li class="text-sm"><a href="#">Tiktok</a></li>
        <li class="text-sm"><a href="#">X</a></li>
        <li class="text-sm"><a href="#">Pinterest</a></li>
      </ul>
    </div>
  </div>

  <hr class="footer-divider" />

  <p class="footer-copy text-sm">©Atelier 2025</p>
</footer>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
    <title>Atelier</title>
</head>
<body>
<!--     Preloader -->
<!--    {% include 'preloader.html' %}-->
<!--     End of Preloader -->
       <!-- Header -->
    <header class="index-header low-nav">
        {% include 'navbar.html' %}
    </header>
    <!-- End of Header -->
  <section class="product-gallery">
  <!-- Rreshti 1: 2 produkte të mëdha -->
  <div class="product-row row-large">
    {% for product in products1|slice:":2" %}
      <div class="product-item large">
        <a href="#">
          <div class="image-wrapper">
            <img src="{{ product.main_image.url }}" alt="{{ product.name }}">
            <div class="collection-label text-medium">{{ product.collection.collection }}</div>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>

  <!-- Rreshti 2: 4 produkte më të vogla me overlay -->
   <div class="product-row row-small">
  {% for product in products1|slice:"2:" %}
    <div class="product-item small">
     <a href="{% url 'product' product.id %}">
      <div class="image-wrapper">
        <div class="product-slider">
  <!-- Main Image first -->
  {% if product.main_image %}
    <img src="{{ product.main_image.url }}" alt="{{ product.name }}" class="slide-image active">
  {% endif %}
  <!-- Other gallery images -->
  {% for image in product.images.all %}
    <img src="{{ image.image.url }}" alt="{{ product.name }}" class="slide-image">
  {% endfor %}

  <!-- Slider Controls -->
  <button class="prev-btn"></button>
  <button class="next-btn"></button>
</div>
        <div class="color-box">
{% for color_link in product.e_product_color_set.all %}
  <span class="color-square" style="background: {{ color_link.color.code }}"></span>
{% endfor %}
        </div>
        <div class="product-overlay">
          <div style="display: flex; justify-content: space-between; align-items: center;">
          <p class="product-name text-small">{{ product.name }}</p>
          <span class="product-price text-small">{{ product.price|floatformat:0 }} EUR</span>
          </div>
          <div style="display: flex; justify-content: end; align-items: center;">
              <i class="far fa-heart wishlist-icon"
                 data-product-id="{{ product.id }}"
                 style="cursor: pointer; color: #ccc;">
              </i>
        </div>
      </div>
      </div>
     </a>
    </div>
  {% endfor %}
</div>

<!--    &lt;!&ndash; Rreshti 1: 2 produkte të mëdha &ndash;&gt;-->
<!--  <div class="product-row row-large">-->
<!--    {% for product in products2|slice:":2" %}-->
<!--      <div class="product-item large">-->
<!--        <a href="#">-->
<!--          <div class="image-wrapper">-->
<!--            <img src="{{ product.main_image.url }}" alt="{{ product.name }}">-->
<!--            <div class="collection-label text-medium">{{ product.collection.collection }}</div>-->
<!--          </div>-->
<!--        </a>-->
<!--      </div>-->
<!--    {% endfor %}-->
<!--  </div>-->
<!--  &lt;!&ndash; Rreshti 2: 4 produkte më të vogla me overlay &ndash;&gt;-->
<!--  <div class="product-row row-small">-->
<!--  {% for product in products2|slice:"2:" %}-->
<!--    <div class="product-item small">-->
<!--    <a href="{% url 'product' product.id %}">-->
<!--      <div class="image-wrapper">-->
<!--        <div class="product-slider">-->
<!--  &lt;!&ndash; Main Image first &ndash;&gt;-->
<!--  {% if product.main_image %}-->
<!--    <img src="{{ product.main_image.url }}" alt="{{ product.name }}" class="slide-image active">-->
<!--  {% endif %}-->
<!--  &lt;!&ndash; Other gallery images &ndash;&gt;-->
<!--  {% for image in product.images.all %}-->
<!--    <img src="{{ image.image.url }}" alt="{{ product.name }}" class="slide-image">-->
<!--  {% endfor %}-->

<!--  &lt;!&ndash; Slider Controls &ndash;&gt;-->
<!--  <button class="prev-btn"></button>-->
<!--  <button class="next-btn"></button>-->
<!--</div>-->
<!--        <div class="color-box">-->
<!--{% for color_link in product.e_product_color_set.all %}-->
<!--  <span class="color-square" style="background: {{ color_link.color.code }}"></span>-->
<!--{% endfor %}-->
<!--        </div>-->

<!--        <div class="product-overlay">-->
<!--          <p class="product-name text-small">{{ product.name }}</p>-->
<!--          <span class="product-price text-small">{{ product.price|floatformat:0 }} EUR</span>-->
<!--        </div>-->

<!--      </div>-->
<!--    </a>-->
<!--    </div>-->
<!--  {% endfor %}-->
<!--</div>-->
</section>
       <!-- Footer -->
       {% include 'footer.html' %}
        <!-- End of Footer -->
<div class="shopping-cart-modal" id="cartModal" style="display:none;">
  {% include 'cart_modal.html' %}
</div>

    <!-- Scripts -->
    {% include 'scripts.html' %}
    <!-- End of Scripts -->
<!-- Preloader -->
<script>
    window.addEventListener("DOMContentLoaded", function () {
        setTimeout(function () {
            const loader = document.getElementById("preloader");
            if (loader) {
                loader.classList.add("hide");
            }
        }, 5000);
    });
</script>
<!-- End of Preloader -->
</body>
</html>

templates/navbar.html
{% load static %}
<div class="main-navbar">
  <div class="navbar-left">
    <a href="/"><img src="{% static 'images/logo-nav.png' %}" alt="Logo img" class="logo"></a>
     <ul>
      <li><a href="#" class="text-sm">Collection</a></li>
      <li><a href="#" class="text-sm">Shop</a></li>
      <li><a href="#" class="text-sm">Explore</a></li>
    </ul>
  </div>
  <div class="navbar-right">
<!--  <a href="#"><img src="{% static 'images/search.png' %}" alt="Search Icon" class="icon-img"></a>-->
  <div class="search-toggle-container">
  <button class="search-icon" id="searchToggle">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="11" cy="11" r="8"></circle>
      <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
    </svg>
  </button>
</div>

<div class="fullpage-search-container" id="searchContainer">
  <div class="fullpage-search-bar">
      <div class="search-input-container">
      <input class="text-sm" type="text" placeholder="Search here..." id="searchInput">
      <button class="close-search" id="closeSearch">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
      </button>
    </div>
    <div class="suggestions">
  <div class="suggestions-grid">
    <div class="categories-column">
      {% for category in categories %}
      <div class="category-group">
        <div class="subcategories">
          {% for subcategory in category.b_subcategory_set.all %}
          <a href="#" class="text-small">{{ subcategory.subcategory }}</a>
          {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="products-column">
      <div class="popular-products">
        {% for product in popular_products %}
        <div class="product-card">
          <img src="{{ product.main_image.url }}" alt="{{ product.name }}">
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
  </div>
</div>

<!--    <a href="#"><i class="icon-user"></i></a>-->
<!--    <a href="#"><i class="icon-heart"></i></a>-->
    <!-- Navbar Heart Icon -->
<a href="#" id="wishlist-icon" data-bs-toggle="modal" data-bs-target="#wishlistModal" class="position-relative">
  {% with wishlist=request.session.wishlist %}
    {% if wishlist %}
      <i class="fas fa-heart"></i>
    {% else %}
      <i class="far fa-heart"></i>
    {% endif %}
<!--    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="wishlist-count">-->
<!--      {{ wishlist|length }}-->
<!--    </span>-->
  {% endwith %}
</a>
<!--    <a href="#" class="text-sm">Shopping cart</a>-->
    <a href="#" id="openCartBtn" class="text-sm cart-toggle"><span>Shopping cart <i class="bi bi-handbag"></i> <span id="cart-total">{{ cartItems }}</span></span><span class="underline"></span></a>
  </div>
</div>

<!-- Wishlist Modal -->
<div class="modal fade" id="wishlistModal" tabindex="-1" aria-labelledby="wishlistModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="wishlistModalLabel">Wishlist</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="wishlist-items">
        <!-- Këtu do ngarkohet lista e produkteve me AJAX -->
        <p>Loading wishlist...</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <!-- Mund të shtosh button "Checkout" ose "Clear wishlist" nëse do -->
      </div>
    </div>
  </div>
</div>

templates/preloader.html
{% load static %}
<div class="preloader" id="preloader">
    <div class="preloader-inner">
        <div class="content">
            <img src="{% static 'images/logo-nav.png' %}">
        </div>
    </div>
</div>